### ISSUE TITLE
is there a way to set shell as a default repl if it doesn't recognize the filetype? 

### ISSUE THREAD

**Issue by psunanand** [urbainvaes/vim-ripple#10]
Thanks for the great plugin. Your plugin made me switch from neoterm because I encountered some problem when sending a python function and I would need to go to the terminal to hit <cr>.

I'm not too sure if I'm asking the right question or not. Probably explaining my workflow will help you understand what I'm currently having a hard time with. There are 2 primary languages that I deal with daily : python and scala-spark. With python, it works perfectly fine. But with scala-spark I can't really figure out how. Normally I would open another terminal window within nvim, and run a docker container to have ipython (with scala-spark kernel) there. Then I could send commands from one window to the other and see the results.

Any suggestion would be very welcome, and let me know if you need more details.
Thanks in advance

**Comment by psunanand** [comment]
Since sending python code to ipython seems to be a real problem here, I found an easy way out by setting scala-spark to open zsh as its repl and then I can work fine with my scala-spark, and have no complains about when sending multiple lines when it comes to python. Thanks again for this minimal plugin !

**Comment by urbainvaes** [comment]
Hi psuanand, 

Many thanks for your suggestion! Adding a fallback REPL for filetypes with no associated REPL wouldn't be too difficult, I think, so we could do this if necessary. But it seems that your solution works, so I suggest we don't make changes yet.

**Comment by psunanand** [comment]
Thanks so much for your quick response. Again, really appreciate this minimal design of the plugin.
