### ISSUE TITLE
Is it possible to add these 2 extra features ?

### ISSUE THREAD

**Issue by psunanand** [urbainvaes/vim-ripple#11]
Thanks again for this plugin. I have been using it for the past days, and there is something that I think it would be great to have:
1. When you close terminal window, you can't reopen it unless you leave that vim instance. 
2. Could it be a side effect from the first question, I was expecting to have different terminals for different vim tabs but it seems that for each vim instance, we can only have one kind of terminal ?

**Comment by urbainvaes** [comment]
Hi psuanand,

Thank you for these suggestions. For the first suggestion, what do you mean exacly? If the terminal window is closed but the buffer still exists, you can access it via `:b term<cr>` or something similar, no?

You are correct about the second issue; at the moment, there can be only one terminal per vim instance. We could probably do 1 instance per filetype without too much difficulty? Would this solve your issues?

**Comment by psunanand** [comment]
For the first issue, I already tried something. As long as I don't delete the buffer I can do something like :vert sb to deal with it. Sorry for this beginner's mistake. I didn't play with it long enough before I raised an issue.

One instance of terminal per filetype is great. Imagine if you split your workspace by the built-in tabs, the first tab is scala-spark to preprocess the data, and the second tab is python to do some analysis. I would say that the ability to run your code and get an instant feedback from repl is super useful, but other than that I might have the third tab writing some bash script and split another window to do something in shell without the need of this plugin.

What do you think ?

**Comment by urbainvaes** [comment]
Hi psuanand,

Let's go for one instance per filetype, then. I'll probably have some time to work on this during the weekend — I'll keep you informed.

**Comment by urbainvaes** [comment]
Hi psuanand,

I have started working on a tentative implementation here: https://github.com/urbainvaes/vim-ripple/commit/fd3942e156b033fe8a0535cdc424bfcccf716abd

I will merge it into master after I test it a bit more, probably this weekend, but feel free to try it already. :)

**Comment by psunanand** [comment]
Thanks so much. I will try it out too since with this feature there is no need to exit vim : )

**Comment by urbainvaes** [comment]
Just FYI, I merged the feature in master. Many thanks again for your input!
