### ISSUE TITLE
Send ripple issue

### ISSUE THREAD

**Issue by ccaprani** [urbainvaes/vim-ripple#12]
Hey, thanks for this plugin - exactly what I'm looking for to expedite development!

I'm on Windows and neovim, and when sending the motion two differences to the gif animation happen:

1. I get a `^U` at the start of each code block sent. I guess this is related to the windows clipboard. I've had a look at the code abut don't know enough to help unfortunately.

2. The sent lines do not get executed. Is this because there is no `<cr>` in the `ripple.vim` mapping?

Issue #1 is the main one to fix as it is easy to move to the terminal and hit enter.

**Comment by urbainvaes** [comment]
Hi, and thanks for reporting the issue.

For the first issue, I think this is because `^U` (and maybe also other readline mappings) doesn't work in the REPL your `ipython`? Can you try to define this in your `.vimrc` and see if it fixes the issue?
```
let s:default_repls = { "python": ["ipython", "\<esc>[200~", "\<esc>[201~", 1] }
```

**Comment by ccaprani** [comment]
Hey @urbainvaes sorry for the delay in getting back to you. That worked perfectly for the `^U` issue- thank you! 

For the other one, even though you have turned on the `{extra_cr}` boolean, should I still add another `<cr>` at the end of the second string above to get it to execute in `ipython`: 

    let g:ripple_repls = { "python": ["ipython", "\<esc>[200~", "\<esc>[201~<cr>", 1] }

**Comment by urbainvaes** [comment]
Hi @ccaprani, many thanks for the update!

For the second issue, could you try to run the following commands, in normal mode in a terminal buffer:

```vim
:let text="\<c-u>\<esc>[200~'hello'\<esc>[201~\<cr>"
:echom text
:put =text
```
The `echo` should print `^U^[[200~'hello'^[[201~^M`, and the `put =text` should write `'hello'` and execute the line. Is this what you observe?

**Comment by ccaprani** [comment]
Hi @urbainvaes, thank you. Yes, the `echom` gives:

    ^U^[[200~'hello'^[[201~^M

but the `put` writes:

    ^U'hello'

and a new line in the terminal buffer.

**Comment by urbainvaes** [comment]
Hi @ccaprani, thanks for following up. So it adds a new line, but does not execute the command? I assume pressing `Enter` manually in the terminal buffer works, at least? :) If it does, could you try:
```
```

**Comment by ccaprani** [comment]
No worries, and thank you again :-)

    :call feedkeys("a".text)

produces nothing in the terminal buffer - a quick flash that I cannot catch. 

    :echom nr2char(getchar())

and pressing return twice does indeed produce `^M` in the command window.

**Comment by urbainvaes** [comment]
All right, thanks, then I have no idea what the issue could be... I'll try to test it on windows in the weekend.

**Comment by ccaprani** [comment]
Hi @urbainvaes : I've upgraded to neovim 0.5 and the `"\<esc>[200~"` and `"\<esc>[201~"` now appear as pre- and post-pended to the motions sent. So I changed that command as follows:
```vim
let g:ripple_repls = { "python": ["ipython", "\<esc>", "\<esc>\<cr>", 1] }
```
And (of course) the symbols are no longer sent. However, the motion still does not get executed, i.e. the `\<cr>` is not being interpreted.

Definitely not a complaint, just an FYI for Windows (though powershell in case that matters).

**Comment by urbainvaes** [comment]
Hi Colin,

Thank you very much for bringing this to my attention!

I had this problem also on linux, and so I changed to terminal input method from `put =@` to `call chansend()`, which fixed the issue for me. Does the issue persist after updating the plugin?

**Comment by ccaprani** [comment]
No worries @urbainvaes ! Thanks as ever for the work. 

I've really been trying to solve this one today - determined!! I've played around with numerous control sequences from [here](https://vt100.net/docs/vt100-ug/chapter3.html#S3.3.2) but can't seem to get any to work (including `\033[015` which *should* work). 

I found a similar issue reported with another neovim plugin [here](https://github.com/kassio/neoterm/issues/171#issuecomment-344291532) which suggests that `\r` should work, but no dice. Maybe I'm misunderstanding something about their solution?

Right now the cleanest results (i.e. no control characters or too many additional empty lines) come from:
```vim
let g:ripple_repls = { "python": ["ipython", "", "", 0] }
```
but it is still required to manually enter the terminal window, enter insert mode, and press enter. There is still one additional empty line in the console. Is there any chance that the `\<cr>`s that are in the `ripple.vim` code around Line 280 or so make any difference? I doubt it since the post-pended characters will come after these in any case.

**Comment by urbainvaes** [comment]
Hi @ccaprani ,

Thank you very much for the detailed account of everything you tried to solve the issue. I frequently get confused about the differences between `\n`, `\r`, `\r\n`, `^M`, and `\<cr>` too, so it's very possible that the plugin uses the wrong ones in certain places.

Most of the issues you linked are quite old, though, so if things were working correctly before Neovim 0.5 (were they?), it's not clear that the information they contain is useful for us.

**Comment by ccaprani** [comment]
@urbainvaes - it wasn't working either before neovim 0.5 (the opening post in this thread), but the symptoms were different (your solutions). For Windows, now the best is to use the repl dictionary above plus manually executing the code. Hardly a massive chore, but still would be nice to figure out.

**Comment by ccaprani** [comment]
@urbainvaes ~~I am very confused now!~~ I have a hack that works! Here is what I've done:

All 3 of those commands work exactly as you describe. They work for a pre-typed line (e.g. `2+2`) or some code send via a `vim-ripple` motion. Further, they work from either buffer.

I thought then perhaps it might be the escape character since to access the command line of course I must escape from the terminal. However, this doesn't seem to be the case.

What's very weird is that sending `call chansend(the_channel,"2+2\<cr>")` doesn't work, but sending `call chansend(the_channel,"2+2")` followed by `call chansend(the_channel,"\<cr>")` does work.

Hence, in the vim-ripple function `s:send_to_buffer(formatted)` I added the following under the `has("nvim")` if block call
```vim
    if has("win32")
        echom "Sending <cr> to '".getbufvar("%", '&channel')."'"
        call chansend(getbufvar("%", '&channel'), "\<cr>")
    endif
```
but this doesn't work, it just adds a new (blank) line into the ipython terminal. 

But this does give a big clue as to what is happening - it seems to be that the `\<cr>` is only getting properly executed once (for want of a better word) "focus" is lost on the terminal buffer, which is what the surrounding commands in the body of `s:send_to_buffer(formatted)` seem to manage. Therefore I added the following to the very end of `s:send_code(...)` (below line 292):
```vim
    if has("win32")
        call s:send_to_buffer("\<cr>")
    endif
```
And this works! 

I don't know enough vimscript (in fact I know zero!) to figure out exactly why the `chansend` doesn't work in the `s:send_to_buffer(formatted)` function body. I did try putting `chansend(getbufvar("%", '&channel'), "\<cr>")` in various places there but none worked - it really needs its own fresh call for some reason. There is still an additional `<\cr>` causing a new line in the terminal but this isn't a big deal. 

So I think the steps from here are:

- maybe the hack is adequate - is it only needed on Windows and for nvim (i.e. does it need a `has("win32") and has ("nvim")`?
- might be nice to understand why the `tabnext` and similar commands affect the `chansend` of `\<cr>`
- Maybe see if the additional `<\cr>` can be found and removed?

**Comment by urbainvaes** [comment]
Hi @ccaprani ,

It's great you found a hack that (at least partially) works; thank you for taking the time to investigate the issue so thoroughly! Computers sometimes behave in mysterious ways…

The additional `<cr>` probably comes from the `newline` variable that is appended to code in `s:send_code`. Perhaps removing this will fix your remaining issue? I tried implementing your hack in a different branch, in wihch `s:send_to_buffer` is called with the `\<cr>` separately. It is available with
```vim
Plug 'urbainvaes/vim-ripple', { 'branch': 'testing' }
```
In case this works on Windows, I will merge the changes into master (the branch also contains a few other unrelated changes).

The `tabsplit` trick, in principle, is not necessary with `chansend`, but it is useful for the `put =` and `feedkeys` input methods. I'll probably remove it at some point, unless it somehow plays a role with this issue.

**Comment by ccaprani** [comment]
So pleased to help out and give back - cheers! 

I've loaded the testing branch and can report (in terms of the default mappings):
- `yr<cr>`  adds and extra line and does not automatically execute
- `yrr` adds an extra line and executes, regardless of indent.
- `yrw` (on variable) does not add an extra line and executes
- `R` (visual mode) does not add an extra line and executes, regardless of indent
- `yp` just repeats the above behaviour.

I can look at this a bit more tomorrow if needed, but I reckon you might know straight away from the above?

**Comment by urbainvaes** [comment]
Great, so things seem to work more or less as intended, except with `yr<cr>` (and perhaps also `yrip`, I would imagine?), if I understand correctly?

**Comment by ccaprani** [comment]
Hmmm, `yrip` works fine: has that additional line, but executes. So it is only `yr<cr>` that doesn't execute.

I can't see how the text is getting sent to the terminal window, but I tried adding the 
```vim
    if has("win32") && has("nvim")
        call s:send_to_buffer("\<cr>")
    endif
```
to the end of the `open_repl` function, but it doesn't work - just adds an additional newline.

**Comment by urbainvaes** [comment]
All right, thanks. I won't make any additional changes on this for now, but I'll try to get access to a Windows computer at some point, so that I can run some tests. I'll keep you informed of any progress I make.

In principle, `open_repl` should be called only once per REPL, at the the first invocation of `yr<motion>` or `y<cr>`, so it's unlikely that changing this function will fix things.

**Comment by ccaprani** [comment]
I've looked at this again and realize I've messed up - apologies - I briefly confused `y<cr>` and `yr<cr>`, hence the silly comment about editing `open_repl` - it should have been `send_buffer` that I looked at. 

So the situation is, after opening a code file (I'm testing with python), pressing:

1. `y<cr>` opens the terminal buffer (ipython) and when followed by `yr<cr>` executes properly (additional newline, but no big deal)
2. `yr<cr>` directly, opens the terminal and 'pastes' the code, but does not execute.

Sorry for the confusion - hope this is clear, and if you want me to test anything, I'll be happy to help. Cheers!

**Comment by urbainvaes** [comment]
Hi @ccaprani ,

I just tried the plugin on Windows, and indeed I am noticing some issues.

It's quite strange that
```vim
:call chansend(the_channel, "2") | call chansend(the_channel, "\<cr>")
```
doesn't work but
```
:call chansend(the_channel, "2") | sleep Xms | call chansend(the_channel, "\<cr>")
```
does work (at least in my virtual machine) for X sufficiently large.

It seems that this "sleep trick" can be used also in the plugin. In the new commit on `testing`, I added a `sleep` just before sending `<cr>`, and this seems to fix most issues. Could you see if setting
```vim
let g:ripple_delay="500ms"
let g:ripple_sleep_hack="500ms"
```
fixes your issues somewhat? 

One issue you report that I don't experience is the additional newline. Are you sure this is not due to the `addcr` we discussed at the beginning of this thread?

Thanks again!

**Comment by ccaprani** [comment]
@urbainvaes Nice idea! 

The fix seems to work whether or not I specify those sleep settings in my init.vim.

The additional line no longer shows up.

The fix works for `yr<cr>` too!

The only obstacle now to pure perfection is that single word motions no longer execute: `yriw` or yriW` for example.

**Comment by urbainvaes** [comment]
It's great that it works, even though the fix might not be very robust!

Regarding executing single words, this was actually by design, but you are not the first to request this, so I decided to add the option `let g:ripple_always_return` which defaults to 0 but you can set it to 1. Hopefully it works as expected!

**Comment by ccaprani** [comment]
@urbainvaes Checked everything thoroughly and it's purring along like a dream now! Thank you so much for the wonderful work!

An FYI in case of future queries: when a terminal is not already open, the `yr<cr>` only executes if the sleep hack and delay are specified.

**Comment by urbainvaes** [comment]
Thanks for the FYI!
