### ISSUE TITLE
Send motion to REPL not appending necessary strings to the code

### ISSUE THREAD

**Issue by peaceamongworlds** [urbainvaes/vim-ripple#14]
Hi, thanks very much for making this plugin!

I'm currently writing a lot of Hy code. Hy being a lisp, the command `yrab` is really useful to send an S-expression to the REPL. Also, something like `yriw` is nice to just look at the value of a variable.

However any command of the form `yra*` or `yri*` doesn't seem to append the strings defined in the configuration or an extra `<cr>`, so the nothing is run in the REPL until I manually enter `<cr>`.

Note that using `yrr` does append an a `<cr>` at the end, so the code is actually executed in the REPL.

This is the relevant config:
```
let g:ripple_repls = {  "hy": ["hy --spy", "", "\n", 1]   }
```

A simple example, file `test.hy`, cursor positioned at `|`:
```hy
(|print 5)
```
When I do `yrr`, the entire line is sent to the REPL along with multiple extra newlines, but for `yrab`, the S-expression is sent, but not run.

Is there a way for me to set it up so that using `yrab` would also allow me to run the expression in the REPL?

**Comment by urbainvaes** [comment]
Many thanks for reporting this!

I can indeed reproduce the behaviour you describe. 

The issue seems to come from the fact that "\n" and "\<cr>" are interpreted differently in the `nvim` term (the issue does not seem to arise in `vim`). If you use `nvim`, could you try replacing `\n` by `\<cr>` in your config? This fixes it for me.

**Comment by peaceamongworlds** [comment]
Thank you! I am using `neovim` and changing `\n` to `\r` fixed the issue.

On an unrelated note, would it be possible to add a feature that would allow one to run a code block at a saved mark? Or maybe save not just the previous code block, but several of the previous ones?

The workflow that I would like to be able to achieve is being able to edit a function, reload it into the REPL, and then run code to test the function. In this case I would be jumping between 2 different points in the code to send it into the REPL, but it would be nice to do it without having to go back and forth.

**Comment by urbainvaes** [comment]
Sonuds like a good idea. You mean something like `<count>yp`, to run the `<count>` previously run block?

**Comment by peaceamongworlds** [comment]
Yeah, I think that would do it

**Comment by peaceamongworlds** [comment]
That sounds even better!

I know that [conjure](https://github.com/Olical/conjure) has an option to run the form under the cursor at a given mark, but that seems quite specific to lisp-like languages. Being able to save a motion to go along with it would make this much more flexible.

**Comment by urbainvaes** [comment]
Hmm, the features of conjure seem to be a bit beyond the scope of this plugin, but thank you for the pointer; I didn't know about that project.

I realized that implementing `2yrr` to run the current line and save it under number `2` confilcts with the current behavious, where `2yrr` just runs the current line and the next. So I opted to use the registers for saving bits of code.

For example, to run the current line and the next and save it unded number 3, you could do `"32yrr`, and then run the bit of code again with just `3yp` (this time just a count. It'd be more consistent, but would require more typing, to use registers for both, so I'm not sure yet what's best).

**Comment by urbainvaes** [comment]
Hi @peaceamongworlds

> Is there a way for me to set it up so that using yrab would also allow me to run the expression in the REPL?

This is now possible with
```vim
let g:ripple_always_return = 1
```
