### ISSUE TITLE
Upgrading neovim causes 134 error

### ISSUE THREAD

**Issue by JohnReid** [urbainvaes/vim-ripple#16]
Hi, thanks for the plugin: the simplicity and ease of use are great.

I recently updated from neovim "NVIM v0.5.0-715-gc5ceefca7" to "NVIM v0.5.0-dev+1062-gcc1851c9f". Now when I start the REPL I immediately get the following error:

```
[Process exited 134]
```

My only ripple related configuration is
```
let newline = "\<cr>"
let g:ripple_enable_mappings = 0
let g:ripple_winpos = 'below'
nmap <LocalLeader>ro <Plug>(ripple_open_repl)
vmap <LocalLeader>rs <Plug>(ripple_send_selection)
nmap <LocalLeader>rm <Plug>(ripple_send_motion)
nmap <LocalLeader>rp <Plug>(ripple_send_previous)
nmap <LocalLeader>a <Plug>(ripple_send_motion)ae
nmap <LocalLeader>p <Plug>(ripple_send_motion)ap
nmap <LocalLeader>l <Plug>(ripple_send_motion)_
nmap <LocalLeader><CR> :call ripple#command(0, 0, newline)<CR>
nmap <LocalLeader>w <Plug>(ripple_send_motion)iw
```

I'm not sure if this is a ripple or neovim issue. Any advice on debugging or a fix would be most welcome.

**Comment by urbainvaes** [comment]
Hi, and many thanks for reporting the issue. I'm using Neovim v0.5.0-808, which is a more recent version than yours, but can't reproduce the issue. After what mapping / command does the issue arise? And does the issue arise with all languages?

**Comment by JohnReid** [comment]
Thanks for the quick response. It happens after `<Plug>(ripple_send_motion)_` and `<Plug>(ripple_send_motion)ae` with both python and R file types. I will try a newer version of neovim (I thought I had a recent one but will double check).

**Comment by JohnReid** [comment]
Just discovered `<Plug>(ripple_open_repl)` opens the REPL fine with this message:

```
vim-ripple: Opening an isolated REPL. To open a REPL common to all buffers of filetype 'python', use 'yr<motion>' directly.
```

Thanks for your help, I think this is at least a work-around.

**Comment by urbainvaes** [comment]
It seems that 'ae' is not a text object in Python for me. I tried
`<Plug>(ripple_send_motion)_` but, on my machine, this does not lead to
an error. What if you open the REPL first and then send a text object?

Also, have you tried updating the plugin?

**Comment by JohnReid** [comment]
`ae` is a text object from one of plugins so yes that is unlikely to work in general. I did update all my plugins and I have the same issue. I will continue investigating but I do have the work-around you suggested: open the REPL first, then send a text object. Thanks for your help.

**Comment by JohnReid** [comment]
It looks to me like something has changed in neovim. Given that 0.5.0 is only a [development release](https://github.com/neovim/neovim/releases) and doesn't seem that stable I've actually gone back to 0.4.4 whilst 0.5.0 sorts itself out. Again thanks for your help with this.

**Comment by urbainvaes** [comment]
Thank you again for reporting the issue. If you ever discover the root cause, I'd be interested to know :)
