### ISSUE TITLE
Send word to IPython

### ISSUE THREAD

**Issue by JohnReid** [urbainvaes/vim-ripple#20]
Hi Urbain, first of all thanks for the great plugin.

I have been using it for some time with IPython and neovim on MacOS but I never managed to get it to send a word (often a variable in my code) to the REPL. Recently I did manage to get it to do so by adding another `<cr>` into my `ripple_repls` configuration (see string below before the 1) combined with the following mapping:

```vim
let g:ripple_repls = { "python": ["ipython", "\<c-u>\<esc>[200~", "\<esc>[201~\<cr>", 1] }
nmap <LocalLeader>w <Plug>(ripple_send_motion)iw
```

My question is, am I doing this right? I feel like I'm missing a trick here and it should be easier to configure vim-ripple to send words to the IPython REPL.

**Comment by urbainvaes** [comment]
Hi John,

Many thanks for the good question. I didn't have this use case in mind when writing the plugin, so there isn't at the moment an easy way to achieve what you want.

What you could do is the following:
```
let g:ripple_repls = { "python": ["ipython", "\<esc>[200~", "\<esc>[201~", 1] }
nmap ,w <Plug>(ripple_send_motion)iw:Ripple <c-v><cr><cr>
```
This way, you can still send a motion without `<cr>` if you want to. But if you are happy with always appending `<cr>` to the code chunks sent to the REPL, then your solution is probably best.

If you just want a way of sending a `<cr>` without leaving the python buffer, and don't mind doing this explicitly, then you could just do
```
nmap ,<cr> :Ripple <c-v><cr><cr>
```

**Comment by JohnReid** [comment]
Thanks for the detailed feedback. I had some ideas in mind that your answers show how to implement but my vim scripting skills weren't up to the task! I will try your first suggestion, it looks more elegant than my extra `cr`.

**Comment by urbainvaes** [comment]
Hi @JohnReid ,

Just FYI, soon (or now if you use the testing branch), you will be able to do
```vim
let g:ripple_always_return = 1
```
to always append `<cr>` to motions sent to REPL, without a need for the `<CR>` in your `g:ripple_repls` configuration.
