### ISSUE TITLE
How to deal with __name__ == "__main__"?

### ISSUE THREAD

**Issue by hhoeflin** [urbainvaes/vim-ripple#21]
Hi,

in python scripts it is best practice usually to put all code to be executed behind "if" statement or in a "main" function  

```
def main():
    my_code1
    my_code2

if __name__ == "__main__": 
    do_this()
    do_that()
    main()
```

In ripple, this causes issues when I only want to send a few lines of the code and not the whole "if" block, as the spaces at the beginning of the code lines are also being sent, and the resulting code in the terminal is invalid due to indentation. A similar situation exists if I pack all the code to be executed into a separate "main" function, as I then also have the indent. 

To explain in the code above .... how would I only execute the "do_that" statement? Or only the "my_code2" and remove exactly 1 level of indentation before sending?

And thanks - very nice plugin you wrote!

**Comment by urbainvaes** [comment]
Hi, and thank you for the comments!

Interestingly, sending indented code seems to produce errors only in the python shell, and not in the ipython one, so using iPython could be a good solution, if the possibility is available to you.

Otherwise, you can define a filter to apply to the code before sending it to the terminal. The following configurations should remove undesired indentation  (but keep it when useful).

```vim
function! s:remove_leading_whitespaces(code)
    echom "test"

    " Check if the first line is indented
    let leading_spaces = matchstr(a:code, '^\s\+')

    if leading_spaces == ""
        return a:code
    endif

    " Calculate indentation
    let indentation = strlen(leading_spaces)

    " Remove further indentations
    return substitute(a:code, '\(^\|\r\zs\)\s\{'.indentation.'}', "", "g")
endfunction

let g:ripple_repls = {
    \ "python": ["ipython", "\<esc>[200~", "\<esc>[201~", 1, function('s:remove_leading_whitespaces')]
    \ }
```

**Comment by hhoeflin** [comment]
Cool - thanks for your answer. I will try it out. I am using bpython, so
was not aware that IPython does not have this issue!
