### ISSUE TITLE
Recent commit breaks chunk send to Radian repl in nvim

### ISSUE THREAD

**Issue by geg2102** [urbainvaes/vim-ripple#22]
I have nvim 0.5.0 (stable) and it looks like the new update, specifically: 

```
call chansend(getbufvar('%', '&channel'), a:formatted)
```
Breaks the chunk send to my radian repl. Switching back to 

```
put =a:formatted
```
seems to have fixed the problem.

**Comment by urbainvaes** [comment]
Many thanks for reporting the issue! Actually, the `put =` input method no longer works with `ipython` since Neovim 0.5, which is why I made the change. I pushed a temporary fix, until we find a more robust solution.
