### ISSUE TITLE
Causes recent neovim to segfault sometimes

### ISSUE THREAD

**Issue by urbainvaes** [urbainvaes/vim-ripple#24]
I still haven't identified the cause of the issue, so I'm interested to know if anyone has comments on this...

**Comment by urbainvaes** [comment]
The issue appears to have resolved itself in new versions of Neovim.

**Comment by verbosemode** [comment]
Haven't had any issues with Ripple on Neovim so far. I've been using it probably since Neovim 0.4.4. But I didn't use it with languages other than OCaml and utop as repl. I'm currently on Neovim 0.7.2. Thanks for the nice and lean plugin :-)

**Comment by urbainvaes** [comment]
Great that you have not had issues, and thank you for the kind words :)
