### ISSUE TITLE
Send motion causes the REPL window to become unbearably small?

### ISSUE THREAD

**Issue by thepenguinthatwants** [urbainvaes/vim-ripple#4]
Hi!

Your plugin looks awesome and should be easily replacing the codi plugin I've used.

```
yr (nmap)
yp (nmap)
R (xmap)
```
Tried the python and bash version and seems like its same what to use. The repl window first starts as taking 50% of the size but then when I use a REPL by sending motion by those keystrokes. The window suddenly becomes very small.

**Comment by urbainvaes** [comment]
Hi,

Thank you very much for reporting an issue. Could you share your vim configuration, whether you use vim or nvim, and what motions trigger the issue?

**Comment by urbainvaes** [comment]
(Closed for inactivity and because I couldn't reproduce the bug.)
