### ISSUE TITLE
Support setting REPL local to buffer

### ISSUE THREAD

**Issue by a-mg** [urbainvaes/vim-ripple#6]
Hey, thanks for your work on this great plugin, it's the only REPL plugin that works the way I want, and I love how simple it is.

I have a use case where I want to change the REPL command for a filetype depending on context. For some `<filetype>` I usually want to use command `<repl>`, but when I'm editing an `<filetype>` file in a certain directory (for example), I want to add a flag to the command: `<repl> -lorem ipsum`.

Right now, I'm handling that by overriding `g:ripple_repls["<filetype>"]` with an autocommand, but it would be cleaner and probably more Vim-like to be able to set a buffer-local REPL command. That also helps avoid unexpected behavior after we override the global config, but open a file where the override shouldn't apply.

Here's how I'd imagine it working: I could set `b:ripple_repl` in any buffer where I'd like a custom command. When opening a REPL, ripple would check for a command in this priority order:

1. `b:ripple_repl`
2. `g:ripple_repls["<filetype>"]`
3. `s:default_repls["<filetype>"]`

If you think this fits the spirit of the plugin and doesn't add too much complexity, I'd be happy to go ahead and implement it, write the docs, and file a pull request. But, I wanted to make sure you think it would be a good addition before going ahead.

**Comment by urbainvaes** [comment]
Hello,

Thank you very much for the detailed suggestion. I think a buffer-local setting would be a great addition to the plugin. I've just pushed a commit implementing your suggestion; does it behave the way you'd expect it to? I'll have more time during the weekend to revisit the code and write the docs. Happy to merge any changes you might have in the meantime.

**Comment by a-mg** [comment]
Yes, this works great! I've pulled the commit and it's working as expected for my config. I can't see any changes I would make. Thanks for a quick update.

**Comment by urbainvaes** [comment]
Great, thank you!
